### PR TITLE
As an admin I want to be able to define global tax settings for my shop

### PR DESCRIPTION
**Pull request by vannguyenn**
Testing Instructions:
- Start the app and log in with a valid account
- Navigate to Settings/Checkout/Taxes
image

### CODE REVIEW

**Review by tedraykov — CHANGES_REQUESTED** [review]
Can you wrap both the payments and the taxes in a container with max width. Generally views that span the whole width of the screen should be tables with a lot of data. For such cards, container wrapping is more suitable.

From what I get from the design files, the taxes configuration will be split in two places in the admin: in `Settings > Checkout >  Taxes` and in `Settings > Taxes`? It's a bit weird, but I'm not part of the discussion for Kinetic product decisions, so I'm missing the justification for that.

**Comment by vannguyenn** [comment]
I think the `Settings/Taxes` should be removed since we combine them into the Checkout page. I'll ask Brendan about this

**Comment by tedraykov** [comment]
In that case where are we going to have the specific taxes plugin configuration UI? The stock flat rate taxes plugin requires configuration. We either have to navigate to a new page for the specific tax plugin UI, or use the `Settings > Taxes` view.

Screenshot 2022-09-19 at 13 18 48

**Review by tedraykov — APPROVED** [review]

**Comment by vannguyenn** [comment]
> In that case where are we going to have the specific taxes plugin configuration UI? The stock flat rate taxes plugin requires configuration. We either have to navigate to a new page for the specific tax plugin UI, or use the `Settings > Taxes` view.
> 
> Screenshot 2022-09-19 at 13 18 48

Yes, we have a [ticket](https://app.zenhub.com/workspaces/kinetic-63156c24d5f91c00183040b5/issues/reactioncommerce/kinetic/47) for this case and we're waiting for the wireframe.

**Pull request merged**
