### PR TITLE
As an operator I want to be able to filter on any custom fields that are available on the cart

### LINKED ISSUE #164: As an operator I want to be able to filter on any custom fields that are available on the cart
This is dependent on the [introspection endpoint ](https://github.com/reactioncommerce/reaction/pull/6731)

As an operator I want the system to inspect the Cart schema and be able to filter by any attribute on my custom extended version of the cart.

Additionally I want to select a custom subset of fields that I want to filter on and store that setting in ShopSettings, so that the list of attributes is kept manageable.

### PR DESCRIPTION
**Pull request by vannguyenn**
Resolves #164

Testing Instructions:
- Use branch `feat/promotions` on API for testing
- Start the app and login with a valid account
- Navigate to Promotions
- Click Actions/Create New
- Fill in all required fields
- Scroll down to Promotion Builder section
- Click Add Action
image
 - Click Add Condition
 - Click on `Property` field
image

- Data populated in the dropdown comes from the `introspectSchema` endpoint with the schema name `CartItem`.

### CODE REVIEW

**Review by brent-hoover — DISMISSED** [review]
While this seems to work it's missing a couple of features specified in the original ticket:

> Additionally I want to select a custom subset of fields that I want to filter on and store that setting in ShopSettings, so that the list of attributes is kept manageable.

Also seems to be only CartItem but not the toplevel cart. 

Also does not appear to be doing validation based on the schema?

**Comment by vannguyenn** [comment]
- `Additionally I want to select a custom subset of fields that I want to filter on and store that setting in ShopSettings, so that the list of attributes is kept manageable.` Is this related to Promotions? Or is this a new setting in the Store settings page?
- As I understand, the condition's property is based on the CartItem schema. c/c @vanpho93 to confirm
- I will add validation on the values field.

**Comment by brent-hoover** [comment]
> Is this related to Promotions? Or is this a new setting in the Store settings page?

It should just be for Promotions but honestly I am not sure where the best place to put this in the UX is as we don't really have anywhere for "global" setting for Promotions. Any input @brendan-shea-pm? Open to ideas

**Comment by brendan-shea-pm** [comment]
@zenweasel Can you give some more context on how an operator would use this functionality? Want to make sure I'm thinking about this in the right way. Could this fall under the advanced search and filter functionality we've touched on recently or is this specific only to Promotions?

**Comment by brent-hoover** [comment]
@brendan-shea-pm Yes.

So this feature adds the fields that are available on the cart to the list of attributes you can filter on for inclusions or exclusions. Importantly this would allow any custom fields that the customer has added to be available to filter on. That work is already complete here and works.

However, this list can get really long and there are several fields that you would probably never want to filter on. So the **additional ask** here is to be able to optionally select a subset of fields that you would normally want to filter on and store that list somewhere in Store Settings so that normally when someone goes to that list they would only see those fields. 

Chloe's question is where exactly would that selection go UX-wise, here maybe in some sort of slide out? or would it go in the regular Store Settings even though this is a Promotions-only setting or somewhere else.

I don't think it would be the end of the world if we kept the full list, but it's a nice usability bump to just see your selected subset.

**Comment by tedraykov** [comment]
Is the code review for this PR blocked until a decision is made for the predefined subset of attributes part?

**Comment by vannguyenn** [comment]
I think we can still review the PR except for the part of the selected subset of attributes

**Review by tedraykov — APPROVED** [review]

**Comment by brent-hoover** [comment]
@tedraykov Let's merge this as-is and get these changes in and deal with any issues along the way

**Comment by tedraykov** [comment]
@zenweasel you need to reapprove to merge this PR

**Pull request merged**
