### PR TITLE
As an operator I want to Trigger a promotion based on an Item in the cart

### LINKED ISSUE #138: As an operator I want to Trigger a promotion based on an Item in the cart
- [ ] User can choose the trigger "Item is in cart" 

- [ ] User can use inclusions and exclusions on the trigger to indicate which item(s) or item attributes should activate the trigger ([issue 120](https://github.com/reactioncommerce/kinetic/issues/120))

Mockup  (Promotions / Detail / Item Trigger)  https://www.figma.com/file/vWot2cXXgjcsLpMq4SAX90/Kinetic?node-id=2020%3A54523&t=c9z0pplx66ozEPgb-0

Screenshot 2022-12-11 at 2 19 57 PM
Screenshot 2022-12-11 at 2 22 21 PM

### PR DESCRIPTION
**Pull request by vannguyenn**
Resolves #138 

Testing Instructions:
- Use branch feat/promotions on API to test this feature
- Start the app and login with a valid account
- Navigate to Promotions
- Click on 1 promotion row to navigate to Promotion details page
- Scroll down to Triggers section and change option to `Item is in cart`

Screenshot 2023-01-12 at 08 51 48

Screenshot 2023-01-12 at 08 51 53

### CODE REVIEW

**Review by brent-hoover — CHANGES_REQUESTED** [review]
If I set the number of items to 10, I think I would expect that having 10 items in the cart would trigger the promotion. However the condition is set to `greaterThanExclusive` which means it would need to be 11 before it's triggered. Seems like it should be set to `greaterThanInclusive` which means 10 would be included

Other than that seems to work well

**Review by brent-hoover — APPROVED** [review]
Changing to approve since the text clearly says "greater than".

**Comment by vannguyenn** [comment]
@zenweasel  I think you're right. It should be `greaterThanInclusive`, the text description below saying `Minimum number of items required to trigger promotion`

**Review by tedraykov — APPROVED** [review]
Looks good to me.

**Pull request merged**
