### PR TITLE
As an operator I want to set start and end times for my promotion, in addition to start and end dates

### LINKED ISSUE #161: As an operator I want to set start and end times for my promotion, in addition to start and end dates
- [ ] User can choose an hour and minute on the start and end dates of a promotion window, for example I want my promotion to start at 9:00am on Dec 12th
- [ ] The time should be based on the time zone of the shop

### PR DESCRIPTION
**Pull request by vannguyenn**
Resolves #161 

Testing Instructions:
- Start the app and login with a valid account
- Navigate to Promotions
- Click on one promotion row to go to a Promotion details page
- Scroll down to `Promotion Scheduling` section
- Select start date and time
Screenshot 2023-01-13 at 17 09 33

Screenshot 2023-01-13 at 17 09 39

### CODE REVIEW

**Comment by brent-hoover** [comment]
Before testing this I corrected the issue on the API where it was only accepting Date rather than DateTime. The PR is [here](https://github.com/reactioncommerce/reaction/pull/6761)

Seeing something strange where I set it for one time in the UI and gets set for a different date in the db:

image

image

Not sure what's happening there but seems similar to the issue that @node82 was running into. I am using mostly unchanged Sample Data set.

**Review by brent-hoover — CHANGES_REQUESTED** [review]
Some issues with setting date/time correctly

**Comment by vannguyenn** [comment]
@zenweasel This is expected, the time shown in the UI is based on your local time, then when sending to the API it will be transformed into UTC+0 with the expected date time format. Then we can easily combine this time with the store's timezone to calculate the schedule

**Review by brent-hoover — APPROVED** [review]

**Review by tedraykov — CHANGES_REQUESTED** [review]
Rather than having the two fields' width be defined by the percentage of the container, can we make them wide enough to fit the input content and the placeholder text?
Screenshot 2023-01-18 at 13 54 15
Currently, it's being cropped on smaller devices.
Also, it would be best if we have them aligned vertically on small devices.

**Comment by vannguyenn** [comment]
@tedraykov I updated the PR. Please review again when you have time. Thanks

**Review by tedraykov — APPROVED** [review]

**Pull request merged**
