### PR TITLE
[MCOSS-92] Configure email variables

### PR DESCRIPTION
**Pull request by vannguyenn**
Jira ticket:
- https://jira.mailchimp.com/browse/MCOSS-92
Testing Instructions:
- Start the app and log in with a valid account
- Navigate to Settings/Transactional Emails
- Click on the `Configure` button

Screen Shot 2022-09-08 at 17 10 20

### CODE REVIEW

**Comment by brent-hoover** [comment]
Since we say "In order for email links to work, you must provide an `:orderId` and `:token` in this field. These act as placeholders that are replaced with the correct data in your email template when an order email is generated. For example: http://shop.example.com/my-orders/:orderId?token=:token" should we enforce having this in the URL?

**Comment by brent-hoover** [comment]
URL validation might be a little loose: 
image

**Comment by vannguyenn** [comment]
> URL validation might be a little loose: image

This is still a valid URL based on URL standards. Do we need to be very strict on this?

**Comment by vannguyenn** [comment]
> Since we say "In order for email links to work, you must provide an `:orderId` and `:token` in this field. These act as placeholders that are replaced with the correct data in your email template when an order email is generated. For example: http://shop.example.com/my-orders/:orderId?token=:token" should we enforce having this in the URL?

We could. I could validate the existence of `:orderId` and `:token`

**Comment by brent-hoover** [comment]
> This is still a valid URL based on URL standards. Do we need to be very strict on this?

I think we should do whatever has the best chance of leading the customer to a successful outcome. I don't think a FTP url is going to be valid URL for an "Account Profile Page" so imho we should not allow it.

**Comment by tedraykov** [comment]
Looks good. I agree it's good put strict HTTP and https validation for the URLs. 

Another suggestion is to add a toast for successful and error mutations. The toast is a common component that must be rendered from all over the app. I would suggest introducing a hook that exposes a function that allows generating a toast with minimum effort. Something like:
```
const {enqueueToast} = useToast();
...
enqueueToast({ message: "Something is saved!", severity: "success" })
```

And the useToast internally handles the opening and closing of the toast. It can be implemented in a ToastProvider for example.

Another suggestion is when using forms, you can disable the save button when the form is not dirty, that is, no fields in it are modified.
```
<Formik<EmailVariables>
          onSubmit={handleSubmitEmailVariables}
          initialValues={initialEmailVariablesValues}
          validationSchema={emailVariablesSchema}
        >
          {({ isSubmitting, dirty }) => (
            <Stack component={Form} flex={1}>
              <Drawer.Content>
                <Field
                  component={TextField}
                  name="storefrontHomeUrl"
                  label="Homepage URL"
                />
                ...
              </Drawer.Content>
              <Drawer.Actions
                right={
                  <Stack direction="row" gap={1}>
                    ...
                    <LoadingButton
                      size="small"
                      variant="contained"
                      type="submit"
                      loading={isSubmitting}
                      disabled={!dirty}
                    >
                      Save Changes
                    </LoadingButton>
                  </Stack>
                }
              />
            </Stack>
          )}
        </Formik>
```

**Comment by vannguyenn** [comment]
- I agree that we should disable the form submit button when the form is not dirty
- About the toast, we have this idea on the radar and have an initial discussion here (https://merchstack.slack.com/archives/C02JK2L6VNK/p1659104068076989). We have the toast notification on the User setting pages as an example. But I think we should wait until we have a final decision on how we want to generalize the notification across the app to avoid rework. I will bring this up again in our next meeting. For now, I think this should not block this PR.

**Review by brent-hoover — APPROVED** [review]

**Comment by vannguyenn** [comment]
Hi @tedraykov, could you take a look again when you have a chance? Thanks

**Review by tedraykov — APPROVED** [review]

**Pull request merged**
