### PR TITLE
Attach Homepage URL to 'View Storefront' Link

### LINKED ISSUE #63: Attach Homepage URL to 'View Storefront' Link
Now that we are setting the 'Homepage URL', we should update the 'View Storefront' link in the Sidebar to point to this URL. If a user clicks on this link, it should open in a new tab.

### PR DESCRIPTION
**Pull request by vannguyenn**
Resolves #63 
Testing Instructions:
- Start the app and log in with a valid account
- Navigate to Transactional Emails/Templates
- Click on Configure button

Screen Shot 2022-10-17 at 16 09 17
Screen Shot 2022-10-17 at 16 09 24

- Provide Homepage URL field
- Save Changes and Reload the page
- Click on `View Storefront` button on the sidebar
image

### CODE REVIEW

**Comment by brent-hoover** [comment]
@vannguyenn These PR's should always include testing instructions

**Comment by brent-hoover** [comment]
If I don't have this set it still opens a new tab and just opens Kinetic again? Should this link just not do anything or not appear when the option is not set?

**Review by tedraykov — COMMENTED** [review]
Why can't we edit the storefront URL from `Settings > Shop Details > General` directly? It's more suitable to do it from there than from the email settings.

Another thing I'm noticing is the `View Storefront` stays grayed out after we add the storefront URL until we refresh the page. The problem is `useUpdateShopMutation` isn't invalidating the shop object used to determine whether the `View Storefront` link is disabled or not.

I would suggest using the shop context as a single source of truth for the whole app. Instead of storing only the active shop id there, we can store the whole shop. This way whenever a mutation modifies the shop we can update the local react state in the shop context. Currently, the source of truth for the shop is coming from `account.adminUIShops[primaryShopId]`

**Comment by vannguyenn** [comment]
Thanks @tedraykov, good catch. I don't remember why we're not allowed to update the storefront URL in the general shop settings, but I think it makes sense to add a field there. I keep the storefront URL in the configure email variables form in case the users want to update all URLs at once.

**Review by tedraykov — APPROVED** [review]

**Pull request merged**
