### PR TITLE
As an admin I want to be able to define and configure an address validation service

### PR DESCRIPTION
**Pull request by vannguyenn**
Testing Instructions:

- Start the app and log in with a valid account
- Navigate to Settings/Checkout/Address Validation
Screen Shot 2022-09-23 at 13 55 58
Screen Shot 2022-09-23 at 13 58 32

### CODE REVIEW

**Review by brent-hoover — APPROVED** [review]

**Comment by tedraykov** [comment]
Where does the second address validation service come from?

**Comment by brent-hoover** [comment]
@tedraykov You can author your own address validation service like you do with payment providers

**Comment by tedraykov** [comment]
I get that they are coming from address validation plugins. My question is regarding where the `Smarty Street` AVS is defined. I assume it's a custom plugin added to the API.

**Review by tedraykov — APPROVED** [review]

**Comment by vannguyenn** [comment]
> I get that they are coming from address validation plugins. My question is regarding where the `Smarty Street` AVS is defined. I assume it's a custom plugin added to the API.

I register a new address validation service in the `api-plugin-address-validation-test` plugin locally for testing purpose

**Pull request merged**
