### PR TITLE
Enable/Disable promotions

### LINKED ISSUE #131: As an operator, I want to enable or disable a promotion so that I can control whether it is active
- [ ] User can Disable or Enable a promotion in the Promotions Listing Page by selecting the Enable or Disable option in the Action menu

- [ ] Newly created promotions are Disabled by default

- [ ] Enabled promotions that are in their promotions date window will have an Active status and customers can use the promotion

- [ ] When a promotion is Enabled, any existing carts should be checked to determine if they qualify for the promotion

- [ ] User can change a promotion from Enabled to Disabled

- [ ] Disabled promotions are not available to customers, even if they are in their promotion date window

- [ ] If an Active promotion is Disabled, the system should stop honoring the promotion and remove all messaging as soon as possible, including all existing carts

Mockup (Promotion Lister) https://www.figma.com/file/vWot2cXXgjcsLpMq4SAX90/Kinetic?node-id=2020%3A54523&t=BCk4dAtpmVYIcdcD-0
Screenshot 2022-11-20 at 2 58 40 PM

### PR DESCRIPTION
**Pull request by vannguyenn**
Resolves #131 , #130, #123

Testing Instructions:
- Use branch feat/promotions on API to test this feature
- Start the app and login with a valid account
- Navigate to Promotions
- Navigate to Disabled tab, select one promotion and click Actions/Enable
image
- Or navigate to a promotion details page, click Actions/Enable

image

### CODE REVIEW

**Review by brent-hoover — CHANGES_REQUESTED** [review]
I was able to enable and disable promotion except I was not able to disable an active promotion. The dropdown only showed "Duplicate"

**Review by tedraykov — CHANGES_REQUESTED** [review]
When I disable an active promotion and then go to the promotion details page I could not enable it back again.

**Comment by brent-hoover** [comment]
When I disable a promotion the toast that pops up says "Disable promotion successfully" but it should say "Disabled promotion successfully". Just the verb tense is wrong. Same with Enable/Enabled

**Comment by brent-hoover** [comment]
I saw the same behavior as Ted, can't Enable a disabled promotion that was once active from the detail view. Was able to enable it again from the Table view.

**Comment by brent-hoover** [comment]
Verified this issue is resolved:
> I was able to enable and disable promotion except I was not able to disable an active promotion. The dropdown only showed "Duplicate"

**Review by brent-hoover — CHANGES_REQUESTED** [review]
Still a couple of small issues

**Comment by brent-hoover** [comment]
If I try to enable an archived promotion it does not work but it does not give me any sort of error message

**Comment by tedraykov** [comment]
A problem not related to the PR, but when the API is down, the error page has regressed:
Screenshot 2023-01-05 at 14 32 35
I got an infinite spinner.

**Comment by tedraykov** [comment]
Here is a problem identified and i'm not sure if I'm doing something wrong, but seems like a bug
https://www.loom.com/share/d465ae9788ee4f81a012aa6d2fc74b99

**Comment by vannguyenn** [comment]
Thanks @tedraykov, that's a bug when disabling a promotion. I have updated the PR

**Review by tedraykov — APPROVED** [review]

**Review by brent-hoover — APPROVED** [review]

**Pull request merged**
