### PR TITLE
Promotion Coupons

### LINKED ISSUE #142: As an operator I want to select a Standard coupon as my trigger
As a user I want to select a Standard coupon as the trigger for my promotion so that my promotion will be triggered by a standard coupon code

- [ ] User can choose the option "Coupon is used (Standard)" from the trigger menu

- [ ] Choosing this option causes the boxes of the Promotion Builder to show coupon name,  coupon code, in store, and inclusion / exclusion boxes in the UI

- [ ] Removing the trigger removes the boxes and returns the Promotion Builder to its default state

Mockup: Promotions / Detail Standard Coupon Trigger https://www.figma.com/file/vWot2cXXgjcsLpMq4SAX90/Kinetic?node-id=2020%3A54523&t=DX1SCEHurQYZHXY8-0

CouponIsUsedStandard

### PR DESCRIPTION
**Pull request by vannguyenn**
Resolves #142, #145, #144, #146

Testing Instructions:
- Use branch `feat/coupons` on API for testing
- Start the app and login with a valid account
- Navigate to Promotions
- Click on one promotion row to go to a Promotion details page
- Scroll down to Promotion Builder section
- Select trigger `Coupon is used (Standard)` option

Screenshot 2023-01-17 at 13 15 40

Screenshot 2023-01-17 at 13 16 12
Screenshot 2023-01-17 at 13 15 51

### CODE REVIEW

**Comment by tedraykov** [comment]
@vannguyenn I'm getting the following error when trying to create a coupon:

Screenshot 2023-01-18 at 13 16 25

```
mutation.js:106 Error: canUseInStore is not allowed by the schema: {"response":{"errors":[{"message":"canUseInStore 
is not allowed by the schema","locations":[{"line":3,"column":3}],"path":["createPromotion"],"extensions":
{"code":"BAD_USER_INPUT","exception":{"errorType":"ClientError","name":"ClientError","error":"validation-error",
"details":[{"name":"canUseInStore","type":"keyNotInSchema","value":false,"message":"canUseInStore 
is not allowed by the schema"}],"stacktrace":["ClientError: canUseInStore is not allowed by the schema"
```

Am i on a wrong branch of the API or something?
I'm using the latest from `feat/promotions`

**Comment by vannguyenn** [comment]
@tedraykov yes, this PR is not ready for review yet. I'm waiting for some changes from the API

**Comment by vannguyenn** [comment]
Move to blocked while waiting for API changes from Brian

**Comment by brent-hoover** [comment]
@vannguyenn can you clarify what changes you are waiting for and that you are working against the coupons branch?

**Review by brent-hoover — CHANGES_REQUESTED** [review]
Need to improve error handling, specifically around duplicate codes and also currently it allows you to input an empty code or a code of all spaces. Also generally errors are not translating into usable feedback for the user

**Review by brent-hoover — APPROVED** [review]
Still have the issue with removing the coupon and then trying to create another one and it won't let you because the coupon has not been deleted but that needs to be fixed on the API side so approving with that one caveat. Error handling is much better.

**Comment by vannguyenn** [comment]
@zenweasel I just integrated this PR with the delete coupon API. Please help to review the missing cases when you have time. Thanks

**Comment by brent-hoover** [comment]
Issue with deletion of coupon triggers resolved

**Review by brent-hoover — APPROVED** [review]

**Review by tedraykov — APPROVED** [review]

**Pull request merged**
