### PR TITLE
Duplicate promotions

### LINKED ISSUE #105: As an operator I want to duplicate an existing promotion and then edit the duplicate rather than building one from scratch
- [ ] User can create a new promotion by duplicating an existing one

- [ ] The new promotion has a unique promotion ID

### PR DESCRIPTION
**Pull request by vannguyenn**
Resolves #105 

Testing Instructions:
- Use branch feat/promotions on API to test this feature
- Start the app and login with a valid account
- Navigate to Promotions
- Select one or multiple promotions 
- Click Actions/Duplicate
image
- Navigate to a promotion details and click Actions/Duplicate
image

### CODE REVIEW

**Review by tedraykov — CHANGES_REQUESTED** [review]
When I try to duplicate a promotion from the details page, it redirects me to `promotions/undefined`
https://www.loom.com/share/ca680ad782694076bade726afe282bc0

**Comment by brent-hoover** [comment]
When I duplicate a promotion that is active, the duplicated promotion is automatically set to active which it shouldn't be. It should be just set to enabled or maybe disabled.

**Review by brent-hoover — CHANGES_REQUESTED** [review]
Except for the issues Ted and I noted, seems good.

**Comment by vannguyenn** [comment]
@tedraykov I think the duplication process has failed somehow, I have added some error messages to notify about this case.
@zenweasel I think this should be improved on API side, I have created a PR for that

**Comment by tedraykov** [comment]
@vannguyenn @vanpho93 @zenweasel https://www.loom.com/share/21f82c6cd4e248d7bf6a2f698ed985a5

**Review by tedraykov — APPROVED** [review]

**Comment by tedraykov** [comment]
@vannguyenn @vanpho93 @zenweasel https://www.loom.com/share/b66c4b3e99584298ab2eb0b73368b094

**Comment by vannguyenn** [comment]
Thanks @tedraykov, I will check the issue on API side

**Comment by vannguyenn** [comment]
Update: I can not reproduce this on my end (with the latest commit on `feat/promotions` on the API side). @zenweasel It could be helpful if you could help to check it when you have time to re-review this PR. Thanks

**Review by brent-hoover — CHANGES_REQUESTED** [review]
When duplicate fails I still don't see an error message in Kinetic. Otherwise it seems to work for me

**Review by brent-hoover — APPROVED** [review]

**Pull request merged**
